export {
  addMotionKeyframe,
  clearFlatNodeMotion,
  clampMotionKeyframes,
  createEditableMotionFromPreset,
  duplicateFlatNode,
  findFlatNodeById,
  getFlatNode,
  insertFlatNode,
  listFlatNodes,
  moveFlatNode,
  normalizeEditableMotion,
  removeFlatNode,
  removeMotionKeyframe,
  setFlatNodeMotion,
  sortMotionKeyframes,
  updateFlatSceneMetadata,
  updateFlatNode,
  updateMotionKeyframe,
  type DuplicateFlatNodeOptions,
  type FlatNodeInsertPosition,
  type FlatSceneMetadataPatch,
} from "./core";
export {
  FLAT_DESIGN_SCHEMA_VERSION,
  FlatDesignDocumentError,
  analyzeFlatDesignDocument,
  assertFlatDesignDocument,
  defineFlatDesignDocument,
  isFlatDesignDocument,
  migrateFlatDesignDocument,
  parseFlatDesignDocument,
  serializeFlatDesignDocument,
  validateFlatDesignDocument,
  type FlatDesignDocument,
  type FlatDesignDocumentAnalysis,
  type FlatDesignDocumentIssue,
  type FlatDesignDocumentIssueCode,
  type FlatDesignDocumentIssueSeverity,
  type ParseFlatDesignDocumentOptions,
} from "./document-contract";
export { compileFlatMotion, resolveFlatMotion } from "./motion";
export type {
  FlatAnimation,
  FlatAnimationTiming,
  FlatAttributeAnimation,
  FlatCircle,
  FlatColorPalette,
  FlatDesignScene,
  FlatEditableKeyframe,
  FlatEllipse,
  FlatGradient,
  FlatGradientStop,
  FlatGroup,
  FlatLayer,
  FlatLength,
  FlatLine,
  FlatMotionCubicBezierEasing,
  FlatMotionDirection,
  FlatMotionEasing,
  FlatMotionEasingPreset,
  FlatMotionFillMode,
  FlatMotionSpec,
  FlatNodePath,
  FlatNodeRef,
  FlatNodeSummary,
  FlatPath,
  FlatPolygon,
  FlatPresetMotionSpec,
  FlatRect,
  FlatShape,
  FlatTimelineMotionSpec,
  FlatTransformAnimation,
} from "./scene-types";
