export {
  addMotionKeyframe,
  clearFlatNodeMotion,
  clampMotionKeyframes,
  compileFlatMotion,
  createEditableMotionFromPreset,
  duplicateFlatNode,
  findFlatNodeById,
  getFlatNode,
  insertFlatNode,
  listFlatNodes,
  moveFlatNode,
  normalizeEditableMotion,
  removeFlatNode,
  removeMotionKeyframe,
  setFlatNodeMotion,
  sortMotionKeyframes,
  updateFlatSceneMetadata,
  updateFlatNode,
  updateMotionKeyframe,
  type DuplicateFlatNodeOptions,
  type FlatNodeInsertPosition,
  type FlatSceneMetadataPatch,
} from "./core";
export {
  FlatSceneEditor,
  type FlatSceneEditorFigureDefinition,
  type FlatSceneEditorFigureFactoryOptions,
  type FlatSceneEditorProps,
  type FlatSceneEditorSelection,
} from "./editor";
export {
  createBobbingAnimation,
  createDriftAnimation,
  createFloatAnimation,
  createOpacityPulseAnimation,
  createPopAnimation,
  createPulseAnimation,
  createSpinAnimation,
  createSwayAnimation,
  createTimelineAnimations,
  type FlatMotionKeyframe,
  type FlatTimelineAnimationOptions,
} from "./animation-presets";
export {
  EditableFlatScene,
  FlatMotionTimelineEditor,
  useFlatSceneSelection,
  type EditableFlatSceneProps,
  type FlatMotionTimelineEditorProps,
  type UseFlatSceneSelectionResult,
} from "./react";
export { FlatScene, type FlatSceneProps, type FlatSceneShapeRenderContext } from "./flat-scene";
export {
  createFlatBadgeFigure,
  createFlatCardFigure,
  createFlatCloudFigure,
  createFlatFigureAnimations,
  createFlatSparkleFigure,
  createFlatSunFigure,
  type FlatBuiltInFigureAnimationPreset,
  type FlatBadgeFigureOptions,
  type FlatCardFigureOptions,
  type FlatCloudFigureOptions,
  type FlatFigureAnimationOptions,
  type FlatFigureAnimationPreset,
  type FlatFigureMotion,
  type FlatSparkleFigureOptions,
  type FlatSunFigureOptions,
} from "./figures";
export { createFlatDesignPalette, defaultFlatDesignPalette } from "./palette";
export { createFlatShowcaseScene, type FlatShowcaseSceneOptions } from "./presets";
export { renderFlatSceneToSvg, type RenderFlatSceneOptions } from "./render-svg";
export type {
  FlatAnimation,
  FlatAnimationTiming,
  FlatAttributeAnimation,
  FlatCircle,
  FlatColorPalette,
  FlatDesignScene,
  FlatEditableKeyframe,
  FlatEllipse,
  FlatGradient,
  FlatGradientStop,
  FlatGroup,
  FlatLayer,
  FlatLength,
  FlatLine,
  FlatMotionSpec,
  FlatNodePath,
  FlatNodeRef,
  FlatNodeSummary,
  FlatPath,
  FlatPolygon,
  FlatPresetMotionSpec,
  FlatRect,
  FlatShape,
  FlatTimelineMotionSpec,
  FlatTransformAnimation,
} from "./scene-types";
