export {
  addMotionKeyframe,
  clearFlatNodeMotion,
  clampMotionKeyframes,
  createEditableMotionFromPreset,
  duplicateFlatNode,
  findFlatNodeById,
  getFlatNode,
  insertFlatNode,
  listFlatNodes,
  moveFlatNode,
  normalizeEditableMotion,
  removeFlatNode,
  removeMotionKeyframe,
  setFlatNodeMotion,
  sortMotionKeyframes,
  updateFlatSceneMetadata,
  updateFlatNode,
  updateMotionKeyframe,
  type DuplicateFlatNodeOptions,
  type FlatNodeInsertPosition,
  type FlatSceneMetadataPatch,
} from "./core";
export {
  FLAT_DESIGN_SCHEMA_VERSION,
  FlatDesignDocumentError,
  analyzeFlatDesignDocument,
  assertFlatDesignDocument,
  defineFlatDesignDocument,
  isFlatDesignDocument,
  migrateFlatDesignDocument,
  parseFlatDesignDocument,
  serializeFlatDesignDocument,
  validateFlatDesignDocument,
  type FlatDesignDocument,
  type FlatDesignDocumentAnalysis,
  type FlatDesignDocumentIssue,
  type FlatDesignDocumentIssueCode,
  type FlatDesignDocumentIssueSeverity,
  type ParseFlatDesignDocumentOptions,
} from "./document-contract";
export { flatDesignDocumentJsonSchema } from "./schema-contract";
export {
  FlatSceneEditor,
  type FlatSceneEditorFigureDefinition,
  type FlatSceneEditorFigureFactoryOptions,
  type FlatSceneEditorProps,
  type FlatSceneEditorSelection,
} from "./editor";
export {
  createBobbingAnimation,
  createDriftAnimation,
  createFloatAnimation,
  createOpacityPulseAnimation,
  createPopAnimation,
  createPulseAnimation,
  createSpinAnimation,
  createSwayAnimation,
  createTimelineAnimations,
  type FlatMotionKeyframe,
  type FlatTimelineAnimationOptions,
} from "./animation-presets";
export { compileFlatMotion, resolveFlatMotion } from "./motion";
export {
  advanceFlatPlayback,
  createFlatPlaybackState,
  restartFlatPlayback,
  seekFlatPlayback,
  setFlatPlaybackPlaying,
  type CreateFlatPlaybackStateOptions,
  type FlatPlaybackState,
} from "./playback";
export {
  getFlatAnimationProgress,
  getFlatShapeAnimations,
  sampleFlatAnimationAtTime,
  sampleFlatSceneAtTime,
  sampleFlatShapeAtTime,
  type FlatAnimatedTransformValue,
  type FlatAnimationSample,
} from "./sampling";
export {
  EditableFlatScene,
  FlatMotionTimelineEditor,
  useFlatSceneSelection,
  type EditableFlatSceneProps,
  type FlatMotionTimelineEditorProps,
  type UseFlatSceneSelectionResult,
} from "./react";
export { FlatScene, type FlatSceneProps, type FlatSceneShapeRenderContext } from "./flat-scene";
export {
  createFlatBadgeFigure,
  createFlatCardFigure,
  createFlatCloudFigure,
  createFlatFigureAnimations,
  createFlatSparkleFigure,
  createFlatSunFigure,
  type FlatBuiltInFigureAnimationPreset,
  type FlatBadgeFigureOptions,
  type FlatCardFigureOptions,
  type FlatCloudFigureOptions,
  type FlatFigureAnimationOptions,
  type FlatFigureAnimationPreset,
  type FlatFigureMotion,
  type FlatSparkleFigureOptions,
  type FlatSunFigureOptions,
} from "./figures";
export { createFlatDesignPalette, defaultFlatDesignPalette } from "./palette";
export { createFlatShowcaseScene, type FlatShowcaseSceneOptions } from "./presets";
export { renderFlatSceneToSvg, type RenderFlatSceneOptions } from "./render-svg";
export type {
  FlatAnimation,
  FlatAnimationTiming,
  FlatAttributeAnimation,
  FlatCircle,
  FlatColorPalette,
  FlatDesignScene,
  FlatEditableKeyframe,
  FlatEllipse,
  FlatGradient,
  FlatGradientStop,
  FlatGroup,
  FlatLayer,
  FlatLength,
  FlatLine,
  FlatMotionCubicBezierEasing,
  FlatMotionDirection,
  FlatMotionEasing,
  FlatMotionEasingPreset,
  FlatMotionFillMode,
  FlatMotionSpec,
  FlatNodePath,
  FlatNodeRef,
  FlatNodeSummary,
  FlatPath,
  FlatPolygon,
  FlatPresetMotionSpec,
  FlatRect,
  FlatShape,
  FlatTimelineMotionSpec,
  FlatTransformAnimation,
} from "./scene-types";
