export {
  createAlignmentModel,
  createParallelTextModel,
  parseAlignment,
  segmentText,
  serializeAlignment,
  type CreateAlignmentModelOptions,
  type CreateParallelTextModelOptions,
  type ParallelTextAlignmentRow,
  type ParallelTextAlignmentSource,
  type ParallelTextModel,
  type ParallelTextParagraph,
  type ParallelTextSentence,
  type ParallelTextToken,
  type ParallelTextTokenLink,
  type SerializedAlignment,
  type SentenceAlignmentInput,
  type TokenAlignmentInput,
} from "./model";
export {
  ParallelTextView,
  type ParallelTextLayout,
  type ParallelTextTranslationOption,
  type ParallelTextViewProps,
} from "./parallel-text-view";
